### ISSUE TITLE
Status lost after HA reboot

### ISSUE THREAD

**Issue by timaseth** [milothomas/ha-miraie-ac#6]
Hi,

Great job getting this going - the HAI community thanks you!

1. Upon reboot of HA, the status of devices returns to `unknown` as the mqtt stat messages are not retained on the local broker.
A quick cure could be to provide a inject node to the MiraAIe node so that we can automate the login post a HA reboot.

2. Some of us like to manually bring devices into HA - would it be possible to allow us to choose our topics?

Thanks again!

**Comment by milothomas** [comment]
Thanks @timaseth, I had started on adding an input to the node so that we can trigger an update on demand.

Regarding point 2, the topics and data follow the spec for hvac mqtt discovery - see the following pages
https://www.home-assistant.io/docs/mqtt/discovery/
https://www.home-assistant.io/integrations/climate.mqtt/

Could you elaborate on why this is required - just trying to understand the problem. If the sole purpose was to "ignore" some devices, perhaps adding a blacklist of device names will help.

**Comment by timaseth** [comment]
@milothomas Thanks for your positive reply!

1. Inject node - awesome, we eagerly wait!

2. HA Discovery topic
Your implementation of auto discovery is spot-on and for a conventional use-case...perfect!
That said, advanced users like to exercise more granular control on both the Miraie platform as well the AC domain (other ACs that they may have). 
Example
a) Wish to have cooling and fan control whereby ignoring auto and dry modes - a very typical use case.
b) Bring all the ACs of the house under one domain/mqtt topic as shown - this helps with automating and things..tidy!
![image](https://user-images.githubusercontent.com/60132339/160265857-9b9a619b-87e5-4023-a3e9-e41fe2401e93.png)

With the option to set the topic name, both type of user-needs are met!

Thanks in advance!

**Comment by milothomas** [comment]
Hey @timaseth, I have released a new version with the input node that you can use to trigger an update.

Now regarding the topics, I am still not very sure what the purpose is but I can look at adding a few config options to specify the mqtt topic prefixes. I say prefixes because the mqtt discovery has some rules around the topics for it to work correctly. Additionally the topics for each device has to be unique and the node needs to map each topic with a device so as to identify the correct device when a message is received from either end (HA -> MirAIe and vice versa)

**Comment by timaseth** [comment]
> Hey @timaseth, I have released a new version with the input node that you can use to trigger an update.
> 
> Now regarding the topics, I am still not very sure what the purpose is but I can look at adding a few config options to specify the mqtt topic prefixes. I say prefixes because the mqtt discovery has some rules around the topics for it to work correctly. Additionally the topics for each device has to be unique and the node needs to map each topic with a device so as to identify the correct device when a message is received from either end (HA -> MirAIe and vice versa)

Thanks!
Perhaps to simplify - not all of us auto discover but prefer to discover on our own using our topics.
Perhaps you may consider giving an output option that spit's out the json - that too could work.
We will live with the 'forced' autodiscovery :-)

**Comment by milothomas** [comment]
> Perhaps you may consider giving an output option that spit's out the json - that too could work.

Yea that shouldn't be a problem 👍
